### ISSUE TITLE
taobao.tbk.spread.get   转短链得接口，这个参数传入总报错

### ISSUE THREAD

**Issue by wang577901673** [ennnnny/tbk#10]
{
    "code": 0,
    "msg": "substr() expects parameter 1 to be string, array given",
    "time": "1578582475",
    "data": null
}

 $params = [
            'requests' => [
                'url' => $url
            ]
        ];

恳求作者帮忙说明下，谢谢

**Comment by lettellyou** [comment]
解决了，url参数还是需要json_encode，我看到你里面处理过了，不知道为啥不行

**Comment by ennnnny** [comment]
其实是因为这个接口请求参数结构特殊，所以我一开始那种处理只是对表层json_encode，所以没效果。已在v0.4.1版修复。
