### ISSUE TITLE
感谢作者，提一个在使用中发现的bug

### ISSUE THREAD

**Issue by aa4933** [ennnnny/tbk#4]
在项目的/tbk/src/Kernel/Support/Helpers.php 的第99行-101行

使用了php5.6不兼容的??双问号写法

发现的来源是这样的，我项目运行环境是7.0，但是脚本运行是5.6，结果出现了异常

**Comment by aa4933** [comment]
这是我的修改方案
 if ((!empty($_SERVER['HTTPS']) && 'off' !== $_SERVER['HTTPS']) || (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) ? $_SERVER['HTTP_X_FORWARDED_PROTO'] : 'http') === 'https') {
        $protocol = 'https://';
    }

**Comment by ennnnny** [comment]
谢谢反馈，已更新
